name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull dcdevdc/aws-app:latest

      - name: Delete old Docker image
        run: sudo docker rm -f dcdevdc/aws-app:latest || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name dcdevdc/aws-app