name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Grant execute permission for gradle
      run: chmod +x gradlew

    - name: Gradle build
      run: ./gradlew build

    - name: Build the Docker image
      run: docker build -t dcdevdc/aws-app:latest .

    - name: Docker images
      run: docker images

    - name: Push to Dockerhub
      run: docker push dcdevdc/aws-app:latest
